// Exercícios padrão da biblioteca
export const EXERCICIOS_PADRAO = [
  // Peito
  {
    nome: 'Supino Reto',
    categoria: 'peito',
    descricao: 'Supino com barra em banco reto',
    forma_execucao: 'Deite no banco, pés no chão, segure a barra com pegada levemente maior que os ombros. Desça a barra até o peito e empurre de volta.',
    musculos_envolvidos: ['peito', 'tríceps', 'ombros'],
    equipamentos_necessarios: ['barra', 'banco'],
  },
  {
    nome: 'Supino Inclinado',
    categoria: 'peito',
    descricao: 'Supino com barra em banco inclinado',
    forma_execucao: 'Banco inclinado em 30-45 graus. Execute o movimento focando na parte superior do peito.',
    musculos_envolvidos: ['peito superior', 'tríceps', 'ombros'],
    equipamentos_necessarios: ['barra', 'banco'],
  },
  {
    nome: 'Crucifixo',
    categoria: 'peito',
    descricao: 'Crucifixo com halteres',
    forma_execucao: 'Deite no banco com halteres, braços estendidos. Abra os braços até sentir o peito esticar.',
    musculos_envolvidos: ['peito'],
    equipamentos_necessarios: ['halteres', 'banco'],
  },
  {
    nome: 'Flexão de Braço',
    categoria: 'peito',
    descricao: 'Flexão de braço tradicional',
    forma_execucao: 'Posição de prancha, mãos alinhadas com os ombros. Desça o corpo e empurre de volta.',
    musculos_envolvidos: ['peito', 'tríceps', 'core'],
    equipamentos_necessarios: ['peso corporal'],
  },
  {
    nome: 'Crossover com Elástico',
    categoria: 'peito',
    descricao: 'Crossover usando elástico',
    forma_execucao: 'Segure o elástico atrás de você, cruze os braços na frente do peito.',
    musculos_envolvidos: ['peito'],
    equipamentos_necessarios: ['elástico'],
  },

  // Costas
  {
    nome: 'Remada Curvada',
    categoria: 'costas',
    descricao: 'Remada com barra inclinada',
    forma_execucao: 'Incline-se para frente, barra na mão. Puxe a barra até o abdômen.',
    musculos_envolvidos: ['dorsal', 'bíceps', 'romboides'],
    equipamentos_necessarios: ['barra'],
  },
  {
    nome: 'Remada Unilateral',
    categoria: 'costas',
    descricao: 'Remada com halter unilateral',
    forma_execucao: 'Apoie uma mão no banco, halter na outra. Puxe o halter até o quadril.',
    musculos_envolvidos: ['dorsal', 'bíceps'],
    equipamentos_necessarios: ['halter', 'banco'],
  },
  {
    nome: 'Puxada na Barra',
    categoria: 'costas',
    descricao: 'Puxada frontal na barra',
    forma_execucao: 'Barra alta, pegada larga. Puxe até o peito, controlando o movimento.',
    musculos_envolvidos: ['dorsal', 'bíceps'],
    equipamentos_necessarios: ['barra fixa'],
  },
  {
    nome: 'Puxada na Polia',
    categoria: 'costas',
    descricao: 'Puxada frontal na polia',
    forma_execucao: 'Sentado na polia, puxe a barra até o peito, contraia as escápulas.',
    musculos_envolvidos: ['dorsal', 'bíceps'],
    equipamentos_necessarios: ['máquina'],
  },
  {
    nome: 'Good Morning',
    categoria: 'costas',
    descricao: 'Good Morning com barra',
    forma_execucao: 'Barra nos ombros, incline-se para frente mantendo as costas retas.',
    musculos_envolvidos: ['eretor da espinha', 'glúteos', 'posterior'],
    equipamentos_necessarios: ['barra'],
  },

  // Pernas
  {
    nome: 'Agachamento Livre',
    categoria: 'pernas',
    descricao: 'Agachamento com barra nas costas',
    forma_execucao: 'Barra nos trapézios, agache até as coxas ficarem paralelas ao chão.',
    musculos_envolvidos: ['quadríceps', 'glúteos', 'posterior'],
    equipamentos_necessarios: ['barra'],
  },
  {
    nome: 'Agachamento Frontal',
    categoria: 'pernas',
    descricao: 'Agachamento com barra na frente',
    forma_execucao: 'Barra na frente dos ombros, mantenha o tronco ereto.',
    musculos_envolvidos: ['quadríceps', 'glúteos'],
    equipamentos_necessarios: ['barra'],
  },
  {
    nome: 'Leg Press',
    categoria: 'pernas',
    descricao: 'Leg Press na máquina',
    forma_execucao: 'Empurre a plataforma estendendo as pernas, não trave os joelhos.',
    musculos_envolvidos: ['quadríceps', 'glúteos'],
    equipamentos_necessarios: ['máquina'],
  },
  {
    nome: 'Afundo',
    categoria: 'pernas',
    descricao: 'Afundo com halteres',
    forma_execucao: 'Passo alternado, mantenha o tronco ereto.',
    musculos_envolvidos: ['quadríceps', 'glúteos'],
    equipamentos_necessarios: ['halteres'],
  },
  {
    nome: 'Stiff',
    categoria: 'pernas',
    descricao: 'Stiff com barra',
    forma_execucao: 'Barra na frente, incline-se para frente mantendo as pernas levemente flexionadas.',
    musculos_envolvidos: ['posterior', 'glúteos'],
    equipamentos_necessarios: ['barra'],
  },
  {
    nome: 'Panturrilha em Pé',
    categoria: 'pernas',
    descricao: 'Elevação de panturrilha em pé',
    forma_execucao: 'Suba na ponta dos pés, contraia a panturrilha no topo.',
    musculos_envolvidos: ['panturrilha'],
    equipamentos_necessarios: ['barra'],
  },

  // Ombros
  {
    nome: 'Desenvolvimento',
    categoria: 'ombros',
    descricao: 'Desenvolvimento com halteres',
    forma_execucao: 'Halters aos ombros, empurre para cima até estender os braços.',
    musculos_envolvidos: ['deltoides', 'tríceps'],
    equipamentos_necessarios: ['halteres'],
  },
  {
    nome: 'Elevação Lateral',
    categoria: 'ombros',
    descricao: 'Elevação lateral com halteres',
    forma_execucao: 'Halters ao lado do corpo, eleve até a altura dos ombros.',
    musculos_envolvidos: ['deltoides lateral'],
    equipamentos_necessarios: ['halteres'],
  },
  {
    nome: 'Elevação Frontal',
    categoria: 'ombros',
    descricao: 'Elevação frontal com halteres',
    forma_execucao: 'Eleve os halteres à frente do corpo até a altura dos ombros.',
    musculos_envolvidos: ['deltoides frontal'],
    equipamentos_necessarios: ['halteres'],
  },
  {
    nome: 'Remada Alta',
    categoria: 'ombros',
    descricao: 'Remada alta com barra',
    forma_execucao: 'Barra na altura da cintura, puxe até o queixo.',
    musculos_envolvidos: ['deltoides', 'trapézio'],
    equipamentos_necessarios: ['barra'],
  },
  {
    nome: 'Arnold Press',
    categoria: 'ombros',
    descricao: 'Arnold Press com halteres',
    forma_execucao: 'Gire os halteres durante o movimento de desenvolvimento.',
    musculos_envolvidos: ['deltoides', 'tríceps'],
    equipamentos_necessarios: ['halteres'],
  },

  // Braços
  {
    nome: 'Rosca Direta',
    categoria: 'braços',
    descricao: 'Rosca direta com halteres',
    forma_execucao: 'Halters na mão, flexione o cotovelo levantando o halter.',
    musculos_envolvidos: ['bíceps'],
    equipamentos_necessarios: ['halteres'],
  },
  {
    nome: 'Rosca Alternada',
    categoria: 'braços',
    descricao: 'Rosca alternada com halteres',
    forma_execucao: 'Alterne os braços em cada repetição.',
    musculos_envolvidos: ['bíceps'],
    equipamentos_necessarios: ['halteres'],
  },
  {
    nome: 'Tríceps Francês',
    categoria: 'braços',
    descricao: 'Tríceps francês com halter',
    forma_execucao: 'Halter atrás da cabeça, estenda o braço para cima.',
    musculos_envolvidos: ['tríceps'],
    equipamentos_necessarios: ['halter'],
  },
  {
    nome: 'Tríceps na Polia',
    categoria: 'braços',
    descricao: 'Tríceps na polia alta',
    forma_execucao: 'Puxe a corda para baixo estendendo os braços.',
    musculos_envolvidos: ['tríceps'],
    equipamentos_necessarios: ['máquina'],
  },
  {
    nome: 'Rosca Scott',
    categoria: 'braços',
    descricao: 'Rosca Scott no banco',
    forma_execucao: 'Braços apoiados no banco Scott, execute a rosca.',
    musculos_envolvidos: ['bíceps'],
    equipamentos_necessarios: ['halteres', 'banco Scott'],
  },

  // Abdômen
  {
    nome: 'Prancha',
    categoria: 'abdômen',
    descricao: 'Prancha isométrica',
    forma_execucao: 'Apoie-se nos cotovelos e na ponta dos pés, mantenha o corpo reto.',
    musculos_envolvidos: ['core', 'reto abdominal'],
    equipamentos_necessarios: ['peso corporal'],
  },
  {
    nome: 'Crunch',
    categoria: 'abdômen',
    descricao: 'Crunch tradicional',
    forma_execucao: 'Deite de costas, levante os ombros do chão.',
    musculos_envolvidos: ['reto abdominal'],
    equipamentos_necessarios: ['peso corporal'],
  },
  {
    nome: 'Crunch Invertido',
    categoria: 'abdômen',
    descricao: 'Crunch com pernas elevadas',
    forma_execucao: 'Deite de costas, eleve as pernas e realize o crunch.',
    musculos_envolvidos: ['reto abdominal', 'quadríceps'],
    equipamentos_necessarios: ['peso corporal'],
  },
  {
    nome: 'Prancha Lateral',
    categoria: 'abdômen',
    descricao: 'Prancha lateral isométrica',
    forma_execucao: 'De lado, apoie-se no cotovelo e mantenha o corpo reto.',
    musculos_envolvidos: ['oblíquos', 'core'],
    equipamentos_necessarios: ['peso corporal'],
  },
  {
    nome: 'Russian Twist',
    categoria: 'abdômen',
    descricao: 'Russian Twist com halter',
    forma_execucao: 'Sentado, gire o tronco de lado a lado com o halter.',
    musculos_envolvidos: ['oblíquos', 'core'],
    equipamentos_necessarios: ['halter'],
  },

  // Cardio
  {
    nome: 'Esteira',
    categoria: 'cardio',
    descricao: 'Corrida ou caminhada na esteira',
    forma_execucao: 'Mantenha um ritmo constante, use inclinação para maior intensidade.',
    musculos_envolvidos: ['quadríceps', 'glúteos', 'cardiovascular'],
    equipamentos_necessarios: ['esteira'],
  },
  {
    nome: 'Bicicleta Ergométrica',
    categoria: 'cardio',
    descricao: 'Pedalada na bicicleta',
    forma_execucao: 'Mantenha cadência constante, ajuste a resistência conforme necessário.',
    musculos_envolvidos: ['quadríceps', 'posterior', 'cardiovascular'],
    equipamentos_necessarios: ['bicicleta'],
  },
  {
    nome: 'Elíptico',
    categoria: 'cardio',
    descricao: 'Treino no elíptico',
    forma_execucao: 'Movimento alternado de braços e pernas no equipamento.',
    musculos_envolvidos: ['corpo inteiro', 'cardiovascular'],
    equipamentos_necessarios: ['elíptico'],
  },
  {
    nome: 'Burpee',
    categoria: 'cardio',
    descricao: 'Burpee completo',
    forma_execucao: 'Agache, flexão, salto. Movimento explosivo do corpo inteiro.',
    musculos_envolvidos: ['corpo inteiro', 'cardiovascular'],
    equipamentos_necessarios: ['peso corporal'],
  },
  {
    nome: 'Mountain Climber',
    categoria: 'cardio',
    descricao: 'Mountain climber',
    forma_execucao: 'Posição de prancha, alterne as pernas rapidamente.',
    musculos_envolvidos: ['core', 'quadríceps', 'cardiovascular'],
    equipamentos_necessarios: ['peso corporal'],
  },
];

// Categorias de exercícios
export const CATEGORIAS_EXERCICIO = [
  'peito',
  'costas', 
  'pernas',
  'ombros',
  'braços',
  'abdômen',
  'cardio'
];

// Equipamentos disponíveis
export const EQUIPAMENTOS_DISPONIVEIS = [
  'barra',
  'halteres',
  'máquina',
  'peso corporal',
  'elástico',
  'kettlebell',
  'banco',
  'barra fixa',
  'polia',
  'esteira',
  'bicicleta',
  'elíptico'
];